### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'netloc'

### ISSUE THREAD

**Issue by linglich** [NLPatVCU/medaCy#107]
#### Description
Hi, I try to install the medacy and medacy_model_clinical_notes model with google colab jupyter notebook.

#### Steps/Code to Reproduce
1. Install medacy - successful
!pip install git+https://github.com/NLPatVCU/medaCy.git
2. Install medacy_model_clinical_notes, not successfully
!pip install git+https://github.com/NLPatVCU/medaCy_model_clinical_notes.git

Collecting git+https://github.com/NLPatVCU/medaCy_model_clinical_notes.git
  Cloning https://github.com/NLPatVCU/medaCy_model_clinical_notes.git to /tmp/pip-req-build-iyx8hwuq
Requirement already satisfied: medacy>=0.0.3 in /usr/local/lib/python3.6/dist-packages (from medacy-model-clinical-notes==1.0.1) (0.0.9)
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 357, in _resolve_one
    add_req(subreq, extras_requested=available_requested)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 314, in add_req
    use_pep517=self.use_pep517
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/constructors.py", line 328, in install_req_from_req_string
    **if req.url and comes_from.link.netloc in domains_not_allowed:
AttributeError: 'NoneType' object has no attribute 'netloc'**

#### Versions

import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import medacy; print("medacy", medacy.__version__)
-->
Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
NumPy 1.14.6
SciPy 1.1.0
medacy 0.0.9

Could anyone help out with this issue please, thank you!

**Comment by AndriyMulyar** [comment]
Please insure you have the latest version of pip install with `pip install
--upgrde pip`

**Comment by AndriyMulyar** [comment]
Hi,

Your issue should now be fixed. It was a problem that emerged with the latest pip version deprecating some functionality. Try the same code again.

**Comment by linglich** [comment]
This works now, thank you!! @AndriyMulyar
