### ISSUE TITLE
Bad input array shape

### ISSUE THREAD

**Issue by sarthak-tg** [NLPatVCU/medaCy#119]
#### Description
I'm getting a error called could not broadcast input array from shape (96) into shape (128)
#### Steps/Code to Reproduce
import medacy_model_clinical_notes
from medacy.model import Model
model = Model.load_external('medacy_model_clinical_notes')
annotations = model.predict("The patient took 5 mg of aspirin.")
#### Expected Results
{
    'entities': {
        'T3': ('Drug', 40, 45, 'Advil'),
        'T1': ('Dosage', 27, 28, '1'), 
        'T2': ('Form', 29, 36, 'capsule'),
        'T4': ('Duration', 46, 56, 'for 5 days')
     },
     'relations': []
}
#### Actual Results
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-1ddde9c61ed4> in <module>
      6 #model = Model(pipeline)
      7 f = open('/usr/local/lib/python3.6/dist-packages/medacy_model_clinical_notes/model/n2c2_2018_no_metamap_2018_12_22_16.49.17.pkl','rb')
----> 8 model1 = medacy_model_clinical_notes.load()
      9 #model = Model.load_external('medacy_model_clinical_notes')
     10 f.close()

/usr/local/lib/python3.6/dist-packages/medacy_model_clinical_notes/medacy_model_clinical_notes.py in load()
      6 def load():
      7     entities = ['Drug', 'Form', 'Route', 'ADE', 'Reason', 'Frequency', 'Duration', 'Dosage', 'Strength']
----> 8     pipeline = ClinicalPipeline(entities=entities)
      9     model = Model(pipeline, n_jobs=1)
     10     model_directory = resource_filename('medacy_model_clinical_notes', 'model')

/usr/local/lib/python3.6/dist-packages/medacy/pipelines/clinical_pipeline.py in __init__(self, metamap, entities)
     22         description="""Pipeline tuned for the extraction of ADE related entities from the 2018 N2C2 Shared Task"""
     23         super().__init__("clinical_pipeline",
---> 24                          spacy_pipeline=spacy.load("en_core_web_sm"),
     25                          description=description,
     26                          creators="Andriy Mulyar (andriymulyar.com)", #append if multiple creators

/usr/local/lib/python3.6/dist-packages/spacy/__init__.py in load(name, **overrides)
     16     if depr_path not in (True, False, None):
     17         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 18     return util.load_model(name, **overrides)
     19 
     20 

/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model(name, **overrides)
    112             return load_model_from_link(name, **overrides)
    113         if is_package(name):  # installed as package
--> 114             return load_model_from_package(name, **overrides)
    115         if Path(name).exists():  # path to model data directory
    116             return load_model_from_path(Path(name), **overrides)

/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model_from_package(name, **overrides)
    133     """Load a model from an installed package."""
    134     cls = importlib.import_module(name)
--> 135     return cls.load(**overrides)
    136 
    137 

/usr/local/lib/python3.6/dist-packages/en_core_web_sm/__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)

/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model_from_init_py(init_file, **overrides)
    171     if not model_path.exists():
    172         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 173     return load_model_from_path(data_path, meta, **overrides)
    174 
    175 

/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    154             component = nlp.create_pipe(name, config=config)
    155             nlp.add_pipe(component, name=name)
--> 156     return nlp.from_disk(model_path)
    157 
    158 

/usr/local/lib/python3.6/dist-packages/spacy/language.py in from_disk(self, path, disable)
    645         if not (path / 'vocab').exists():
    646             exclude['vocab'] = True
--> 647         util.from_disk(path, deserializers, exclude)
    648         self._path = path
    649         return self

/usr/local/lib/python3.6/dist-packages/spacy/util.py in from_disk(path, readers, exclude)
    509     for key, reader in readers.items():
    510         if key not in exclude:
--> 511             reader(path / key)
    512     return path
    513 

/usr/local/lib/python3.6/dist-packages/spacy/language.py in <lambda>(p, proc)
    641             if not hasattr(proc, 'to_disk'):
    642                 continue
--> 643             deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
    644         exclude = {p: False for p in disable}
    645         if not (path / 'vocab').exists():

pipeline.pyx in spacy.pipeline.Tagger.from_disk()

/usr/local/lib/python3.6/dist-packages/spacy/util.py in from_disk(path, readers, exclude)
    509     for key, reader in readers.items():
    510         if key not in exclude:
--> 511             reader(path / key)
    512     return path
    513 

pipeline.pyx in spacy.pipeline.Tagger.from_disk.load_model()

pipeline.pyx in spacy.pipeline.Tagger.from_disk.load_model()

/usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/model.py in from_bytes(self, bytes_data)
    350                         name = name.decode('utf8')
    351                     dest = getattr(layer, name)
--> 352                     copy_array(dest, param[b'value'])
    353                 i += 1
    354             if hasattr(layer, '_layers'):

/usr/local/lib/python3.6/dist-packages/thinc/neural/util.py in copy_array(dst, src, casting, where)
     46 def copy_array(dst, src, casting='same_kind', where=None):
     47     if isinstance(dst, numpy.ndarray) and isinstance(src, numpy.ndarray):
---> 48         dst[:] = src
     49     elif isinstance(dst, cupy.ndarray):
     50         src = cupy.array(src, copy=False)

ValueError: could not broadcast input array from shape (96) into shape (128)

**Comment by AndriyMulyar** [comment]
Seems to be a problem with your thinc installation - spaCy's small model is utilized for extracting POS tags which is causing the error. See here: [https://support.prodi.gy/t/valueerror-could-not-broadcast-input-array-from-shape-64-into-shape-64-1/446](https://support.prodi.gy/t/valueerror-could-not-broadcast-input-array-from-shape-64-into-shape-64-1/446)

**Comment by sarthak-tg** [comment]
My error is solved! The main reason was that the spacy, en_core_web_sm and en_vectors_web_lg versions should be compatible with each other(eg : mine all are at versions 2.0.0). The spacy version 2.0.0 is compatible with medacy version 0.0.9. Thank you!

**Comment by sarthak-tg** [comment]
Medacy does not detect symptoms for a particular patient.
Eg: The patient showed up with a temperature of 100.1F, and a sore throat.

Here I need to detect the temperature and sore throat. It captures medicines very well and accurately.
I need to detect the symptoms as well. Can you help me @AndriyMulyar? Is there any specific library designed for the same?
