### ISSUE TITLE
[FEATURE REQUEST] Add Language model

### ISSUE THREAD

**Issue by MoAbd** [NLPatVCU/medaCy#121]
**What problem does your feature solve?**
can you add Language model for medical notes to predict next word

**Describe the solution you'd like**
adding transformer model , or implementation of the paper 
[Learning to Write Notes in Electronic Health Records](https://arxiv.org/pdf/1808.02622.pdf)

**Comment by swfarnsworth** [comment]
MedaCy is intended to be strictly for named entity recognition, with the intention that it can be integrated into end-to-end solutions that require named entity recognition as a component. I'm not sure that predicting subsequent tokens is sufficiently related to that goal for it to need to be included here.
