### ISSUE TITLE
Problem with installing medaCy

### ISSUE THREAD

**Issue by justachetan** [NLPatVCU/medaCy#128]
#### Description

Hi. I am trying to install medaCy on my system using the instructions given in the README, however, I am getting some error caused due to unavailability of some SpaCy models.

#### Steps/Code to Reproduce

Run:
` pip install git+https://github.com/NLPatVCU/medaCy.git`

#### Output
```


Collecting git+https://github.com/NLPatVCU/medaCy.git
       Cloning https://github.com/NLPatVCU/medaCy.git to /tmp/pip-k5kMwQ-build
Collecting en_core_web_sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm-2.0.0 (from medacy==0.1.0)
        Could not find a version that satisfies the requirement en_core_web_sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm-2.0.0 (from medacy==0.1.0) (from versions: )
No matching distribution found for en_core_web_sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm-2.0.0 (from medacy==0.1.0)


```
#### Versions
- Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-18.04-bionic
- NumPy 1.16.3
- SciPy 1.3.0
- medaCy not installed, the issue is about that only

**Comment by jvargas2** [comment]
@justachetan Have you tried upgrading pip with `pip install -U pip`? If upgrading pip isn't an option then you should be able to download the en_core_web_sm model through spaCy. Other projects have had similar issues with automatically downloading spaCy models: https://github.com/allenai/allennlp/issues/918

**Comment by justachetan** [comment]
Yes, I had to download the model separately. I must say I am kinda disappointed with the performance of the pre-trained models of medaCy.

**Comment by jyaoeplus** [comment]
encounter an error with code line "**from medacy.pipelines import ClinicalPipeline**"
Error message:
ModuleNotFoundError: No module named 'medacy.pipelines':

"pipelines" subdirectory not found under medacy, shown as:
# ls /conda/envs/rapids/lib/python3.6/site-packages/medacy
__init__.py  __pycache__  ner                  relation  tools
__main__.py  data         pipeline_components  tests

how to fix it?
