### ISSUE TITLE
ImportError: Package not installed: medacy_model_clinical_notes

### ISSUE THREAD

**Issue by mdivakaran** [NLPatVCU/medaCy#148]
#### ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-784aecc37831> in <module>
      1 from medacy.ner.model import Model
      2 
----> 3 model = Model.load_external('medacy_model_clinical_notes')
      4 annotation = model.predict("The patient was prescribed 1 capsule of Advil for 5 days.")
      5 print(annotation)

~/anaconda3/lib/python3.7/site-packages/medacy/ner/model/model.py in load_external(package_name)
    458         """
    459         if importlib.util.find_spec(package_name) is None:
--> 460             raise ImportError("Package not installed: %s" % package_name)
    461         return importlib.import_module(package_name).load()
    462 

ImportError: Package not installed: medacy_model_clinical_notes
####

**Comment by Chee-Foong** [comment]
Try this:

pip install git+https://github.com/NLPatVCU/medaCy_model_clinical_notes.git

Works for me
