### ISSUE TITLE
Cannot install medaCy_model_clinical_notes from master

### ISSUE THREAD

**Issue by sema4-EricSchles** [NLPatVCU/medaCy#157]
#### Description

I tried to install medaCy_model_clinical_notes from the code found in the master branch but it gives the error:

```
from medacy.pipelines import ClinicalPipeline
ModuleNotFoundError: No module named 'medacy.pipelines'
```
#### Steps/Code to Reproduce

All you need to do is try to run:

`model = Model.load_external('medacy_model_clinical_notes')`

#### Expected Results

I expect the example to work

#### Actual Results

The above error.

#### Versions

I'm trying to figure out the fix, and will make a PR when I do.

**Comment by sema4-EricSchles** [comment]
The fix was:

Download the source, remove the build and dist directory, and remove the egg, then re-install from the setup.py file.  I needed to do this for both the corpus and the main library.

Steps:

```
git clone https://github.com/NLPatVCU/medaCy.git
cd medaCy
rm -Rf build
rm -Rf dist
rm -Rf medacy.egg-info
python setup.py install

git clone https://github.com/NLPatVCU/medaCy_model_clinical_notes.git
cd medaCy_model_clinical_notes
rm -Rf build
rm -Rf dist
rm -Rf medacy.egg-info
python setup.py install
```
Then you should be good.

**Comment by sema4-EricSchles** [comment]
It's not great that I needed to futz around.  This should be fixed, in a future release, please!

**Comment by sema4-EricSchles** [comment]
@AndriyMulyar @bmcinnes @ytpillai @CoreySutphin

**Comment by swfarnsworth** [comment]
I believe that the problems you were experiencing were my fault because I moved things around prematurely. Are you still experiencing any issues?

**Comment by jayachaturvedi** [comment]
I am facing a similar issue with : model = Model.load_external('medacy_model_clinical_notes')
I get a long error message which I can paste if required. The final message is: error: bad escape \p at position 257

(I am fairly new to python in general so it might be something obvious but i'd appreciate any help)

**Comment by swfarnsworth** [comment]
I recall having this problem in the past. I believe the solution was to update the spaCy English model. Try this command:

`python -m spacy download en_core_web_sm`

If you have installed medaCy in a virtual environment (which we recommend), be sure to activate that environment before running this command. Also, note that the next release of medaCy will automatically install a newer version of en_core_web_sm.

**Comment by jayachaturvedi** [comment]
Thanks so much! That made it work!
