### ISSUE TITLE
Installing clinical notes, module not  found error

### ISSUE THREAD

**Issue by SouvikMondalD** [NLPatVCU/medaCy#158]
Medacy pipeline
```
 from medacy.pipelines import ClinicalPipeline
    ModuleNotFoundError: No module named 'medacy.pipelines'
```

The problem occurs during the installation of the clinical notes model. Is there some inconsistency with respect to the medacy.pipelines name

**Comment by kAgotsi** [comment]
I have a same error when I trying to install a model by  :  pip install git+https://github.com/NLPatVCU/medaCy_model_clinical_notes.git.

**Comment by swfarnsworth** [comment]
Please install the development branch of medaCy:

`pip install git+https://github.com/NLPatVCU/medaCy.git@development`

I recently did a large refactor of medaCy and updated external packages to work with that refactor. In retrospect I should have kept those changes on the development branch of the external packages and merged them all into their respective master branches at once. 

Admittedly I did not expect for the external packages to be used by anyone outside the lab that I work in, but I'm pleased to see that this is not the case. I'm going to check to see if we've made any improvements to the clinical notes model since its last release and, if so, update it so that you can work with it.

**Comment by SouvikMondalD** [comment]
> Please install the development branch of medaCy:
> 
> `pip install git+https://github.com/NLPatVCU/medaCy.git@development`
> 
> I recently did a large refactor of medaCy and updated external packages to work with that refactor. In retrospect I should have kept those changes on the development branch of the external packages and merged them all into their respective master branches at once.
> 
> Admittedly I did not expect for the external packages to be used by anyone outside the lab that I work in, but I'm pleased to see that this is not the case. I'm going to check to see if we've made any improvements to the clinical notes model since its last release and, if so, update it so that you can work with it.


Thanks for specifying the branch. However, I think there are some links to external packages which probably also needs to be updated. For example, during installation of the core medaCy development branch, this shows up:

```
Collecting en_core_web_sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm-2.1.0 (from medacy==0.2.0)
  Could not find a version that satisfies the requirement en_core_web_sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm-2.1.0 (from medacy==0.2.0) (from versions: )
No matching distribution found for en_core_web_sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm-2.1.0 (from medacy==0.2.0)


```
Have you already refactored all the dependencies and imports in the development branch?

**Comment by swfarnsworth** [comment]
Thank you for bringing this to my attention. I will look into the dependencies.

**Comment by karan4894** [comment]
Hi all.
Make sure you update your spacy model. Then follow up instructions to install medacy.
Like this

!python -m spacy download en_core_web_sm

from medacy.model.model import Model

model = Model.load_external('medacy_model_clinical_notes')
annotation = model.predict("Karan Advil boy")
print(annotation)

Hope it works.
