### ISSUE TITLE
Cannot import name 'metamap' from 'medacy.pipeline_components' 

### ISSUE THREAD

**Issue by kAgotsi** [NLPatVCU/medaCy#159]
#### Description

I have this exception when I try to import MetaMap, could you help me fix this bug

#### Steps/Code to Reproduce
from medacy.data import Dataset
from medacy.pipeline_components import metamap
dataset = Dataset('/home/predimed/Documents/NER/data/corpus')
for data_file in dataset:
  print(data_file.file_name)
print(data)
print(data.is_metamapped())

#metamap = Metamap('/home/predimed/Documents/NER/tools/public_mm/bin/')
data.metamap(metamap)
print(data.is_metamapped())

#### Expected Results

file_one
file_two
['file_one.txt', 'file_two.txt']
False
True

#### Actual Results
ImportError                               Traceback (most recent call last)
<ipython-input-2-c61ba796da32> in <module>
      1 from medacy.data import Dataset
----> 2 from medacy.pipeline_components import metamap
      3 dataset = Dataset('/home/predimed/Documents/NER/data/corpus')
      4 for data_file in dataset:
      5   print(data_file.file_name)

ImportError: cannot import name 'metamap' from 'medacy.pipeline_components' (/home/predimed/.local/lib/python3.7/site-packages/medacy/pipeline_components/__init__.py)

#### Versions
Linux-4.19.0-6-amd64-x86_64-with-debian-10.1
Python 3.7.4
NumPy 1.16.1
SciPy 1.3.1
medacy 0.2.0

**Comment by swfarnsworth** [comment]
The name of the class you are trying to import is MetaMap, with both Ms capitalized. When you create the MetaMap object, remember to pass to it the metamap binary file, not the directory containing the binary files.

There are a few other errors in this code sample; if you are not able to resolve them please let me know.

**Comment by swfarnsworth** [comment]
I see that you're using medaCy 0.2.0, but these import statements are from an earlier version of medaCy. This is what that code should look like:

```
from medacy.data.dataset import Dataset
from medacy.pipeline_components.feature_overlayers.metamap.metamap import MetaMap
dataset = Dataset('/home/predimed/Documents/NER/data/corpus')
for data_file in dataset:
    print(data_file.file_name)

print(dataset)
print(dataset.is_metamapped())

#metamap = Metamap('/home/predimed/Documents/NER/tools/public_mm/bin/metamap')
data.metamap(metamap)
print(dataset.is_metamapped())
```
