### ISSUE TITLE
Clinical Notes pre trained model breaks with other examples

### ISSUE THREAD

**Issue by Shelabd** [NLPatVCU/medaCy#161]
#### Description
The Pre trained clincial notes model breaks with any other combination of medicine, dose and duration. 

#### Steps/Code to Reproduce
Replace the existing text to -> "The patient was prescribed 4 capsules of adderall for 6 months"
#### Expected Results
Dose= 4
Type= Capsule
Medicine= Adderall
Duration= 6 months
#### Actual Results
{'entities': {}, 'relations': []}
#### Versions

Linux-4.14.29-linuxkit-x86_64-with-debian-stretch-sid
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0]
NumPy 1.16.1
SciPy 1.1.0
medacy 0.1.1

**Comment by swfarnsworth** [comment]
It appears that the model is not broken, but that it was not trained to properly associate the vocabulary used in your example with their desired labels. No perfect model for this task currently exists. I plan to update this model with a version that is more performant in the future, thanks to developments by one of my colleagues.
