### ISSUE TITLE
Cant install medacy (torch version 1.2.0 error) 

### ISSUE THREAD

**Issue by HarsheetKakar** [NLPatVCU/medaCy#180]
#### Description
Cannot install medaCy in my windows system

#### Steps/Code to Reproduce
pip install git+https://github.com/NLPatVCU/medaCy.git

#### Error
ERROR: Could not find a version that satisfies the requirement torch==1.2.0 (from medacy==0.2.0) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.2.0 (from medacy==0.2.0)

#### Versions
Windows-10-10.0.18362-SP0
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
NumPy 1.17.4
SciPy 1.3.2

**Comment by swfarnsworth** [comment]
Our dependencies do not support Windows, thus medaCy cannot run on Windows. Your machine might come with Hyper V available which would allow you to create a virtual machine that shares hardware resources with your Windows VM.

**Comment by HarsheetKakar** [comment]
> Our dependencies do not support Windows, thus medaCy cannot run on Windows. Your machine might come with Hyper V available which would allow you to create a virtual machine that shares hardware resources with your Windows VM.

ok, thanks for the fast reply

**Comment by joys8998** [comment]
Sorry but i have the same problem:

ERROR: Could not find a version that satisfies the requirement torch==1.2.0 (from medacy==0.2.0) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0)
ERROR: No matching distribution found for torch==1.2.0 (from medacy==0.2.0)

 but in ubuntu 18.04. Even if i install torch manually, i get this error when i try to import medacy:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'medacy'
