### ISSUE TITLE
Module Not Found Error (medacy.ner)

### ISSUE THREAD

**Issue by yellowwoods12** [NLPatVCU/medaCy#186]
#### Description
After installing medaCy from the developement branch and medaCy Clinical Notes I am still getting the following error when I try to run my app.py.

Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from backend.medicine_extractor import *
  File "/mnt/sda1/Documents/minor 2/MedAI-master/backend/medicine_extractor.py", line 1, in <module>
    from medacy.ner.model import Model
ModuleNotFoundError: No module named 'medacy.ner' 

#### Expected Results

Script should run as expected since the latest version of medaCy is installed but somehow it is unable to detect the package.

#### Versions

OS : Ubuntu 18.04
Running the project in a virtual environement.

Kindly let me know what the issue is since I have checked all the other issues reporting a similar problem and tried their solutions but nothin g works.

**Comment by swfarnsworth** [comment]
Hello, please install the latest version of the development branch and the latest version of the model that you are using. I've been meaning to release to master but our development schedule has been affected by the COVID-19 pandemic.

Note that `medacy.ner` is no longer a module within medaCy, so your import statement for model will need to be `from medacy.model.model import Model`; I should probably look into making this less verbose.

Please let me know if you encounter any other issues.
