### ISSUE TITLE
nanomedicine_drug_labels model not found

### ISSUE THREAD

**Issue by gserb-datascientist** [NLPatVCU/medaCy#187]
attempt to install drug label model failed with error
fatal: repository 'https://github.com/NLPatVCU/medaCy_nanomedicine_drug_labels.git/' not found

**Comment by swfarnsworth** [comment]
It appears that my colleague who began this project had envisioned that that model would be created. When this project began, we were using a conditional random field, but we can now use BiLSTM and BERT learners. The former does not require you to have a GPU once the model is created, but it does require a large file of word embeddings available at this website: http://evexdb.org/pmresources/vec-space-models/

Is that something you would be interested to use?
