### ISSUE TITLE
 object 'Dataset' has no attribute 'load_external'

### ISSUE THREAD

**Issue by gserb-datascientist** [NLPatVCU/medaCy#192]
attempt to run
medaCy/examples/scripts/training_predicting.py 

failed with 
AttributeError: type object 'Dataset' has no attribute 'load_external'

**Comment by swfarnsworth** [comment]
That script was written using an older version of the API that existed when we were providing our datasets on GitHub, however we discontinued that practice.

A new release to master is already complete and is pending a code review from my colleagues and my advisor. It is intended that going forward, the command line interface will be the primary means of using the package, but a newer version of the API will of course be available for writing scripts.
