### ISSUE TITLE
Add result -> latex table conversion

### ISSUE THREAD

**Issue by AndriyMulyar** [NLPatVCU/medaCy#20]
Add automatic formatting of LaTeX tables with printed results.

**Comment by daniela-llivina** [comment]
What you need is to generate latex tables with the result of the prediction?

**Comment by AndriyMulyar** [comment]
> What you need is to generate latex tables with the result of the prediction?

Daniela, 
You are right. Thank you for your interest in the project. If you would like to contribute, please get in contact with.

Best,
Andriy

**Comment by daniela-llivina** [comment]
Andriy,
I'd like to contribute. Can I claim this issue?

**Comment by AndriyMulyar** [comment]
> Andriy,
> I'd like to contribute. Can I claim this issue?

Yes please! Please reach out with any questions. You should find the dictionary with computed results in the cross_validate method  of the StratifiedKFoldCrossValidation class.

**Comment by daniela-llivina** [comment]
Hi Andriy,
Where should my code live with in the project?

Best,
Daniela

**Comment by AndriyMulyar** [comment]
Preferably, place into the KFoldCrossValidation class. It will be
refactored as necessary at a later point. Thank you!

**Comment by daniela-llivina** [comment]
The only class that I can find containing "kfold" in its name is
"SequenceStratifiedKFold". Is this the one?

**Comment by AndriyMulyar** [comment]
Yes, my apologies.

**Comment by swfarnsworth** [comment]
As it turns out, you can do this with the CLI for the tabulate module.
