### ISSUE TITLE
Support for Python 2.7

### ISSUE THREAD

**Issue by ahmedch1** [NLPatVCU/medaCy#201]
#### the command that I have launched is : 
 `pip install git+https://github.com/NLPatVCU/medaCy.git`

#### I got this message

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/NLPatVCU/medaCy.git
  Cloning https://github.com/NLPatVCU/medaCy.git to c:\users\wiki\appdata\local\temp\pip-req-build-kknswm
  Running command git clone -q https://github.com/NLPatVCU/medaCy.git 'c:\users\wiki\appdata\local\temp\pip-req-build-kknswm'
ERROR: Package 'medacy' requires a different Python: 2.7.18 not in '>=3.7'
WARNING: You are using pip version 19.2.3, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
`

**Comment by swfarnsworth** [comment]
Python 2.7 is deprecated and we do not support it. Python 3.7 is the oldest version that we plan to support for more than a year from now.

I have not run the unit tests on the newest version of Python (3.9) yet given how recently that version came out, but we ostensibly plan to support it.
