### ISSUE TITLE
Models page not accessible, Not able to download models

### ISSUE THREAD

**Issue by balachander1964** [NLPatVCU/medaCy#202]
### Hi, I am trying to use MedACY for some research work. I am not able to download your models as the page is not accessible. I will appreciate if you let me know from where I can download the models. Thank you in Advance. Wishing you a Merry Christmas and Happy New Year in advance. Bala

**Comment by swfarnsworth** [comment]
What sort of entities do you need for the model to be able to recognize?

**Comment by swfarnsworth** [comment]
Superseded by #203.
